format:
	npm run format

linter: 
	npx prettier --write .

run:
	npm run dev

docker:
	docker build --tag secretnote-fe .
	docker run secretnote-fe

test:
	npm run test:unit

e2e:
	npm run test:e2e

install:
	npm install
