version: '3'
services:
    db:
        image: postgres
        container_name: postgres-db
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres  
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=postgres
            
        ports:
            - '5432:5432'
        network_mode: "host"
