version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    deploy:
      replicas: 1

  backend:
    image: mimo199/secretnotebe:v1.0
    ports:
      - "8080:8080"  
    env_file:
      - .env
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    image: mimo199/secretnotefe:v1.0
    env_file:
      - .env
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

