version: '3'
services:
    db:
        image: postgres
        container_name: postgres-db
        env_file: .env
        environment:
            - POSTGRES_PORT=${POSTGRESQL_PORT}
            - POSTGRES_USER=${USER}  
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_DB=${DBNAME}
        ports:
            - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
        network_mode: "host"
        
    backend:
        build: 
            dockerfile: Dockerfile
        image: secretnote-be
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - db
        env_file:
            - .env

