apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: secretnote
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: secretnote
        tier: backend
    spec:
      containers:
      - name: backend-pod
        image: mimo199/secretnotebe:v1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: secretnote
    tier: backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
