apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels: 
    app.kubernetes.io/name: backend
spec:
  containers:
  - name: backend-pod
    image: mimo199/secretnotebe:v1.1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
