apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels: 
    app.kubernetes.io/name: frontend
spec:
  containers:
  - name: frontend-pod
    image: basem1166/secretnotefe:v1.6
    ports:
    - containerPort: 80
    env:
      - name: VITE_BASE_URL
        valueFrom:
          configMapKeyRef:
            name: frontend-configmap
            key: VITE_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001