apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: secretnote
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: secretnote
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: basem1166/secretnotefe:v3.0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: secretnote
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80