name: Go

on: push 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
      
    - name: format
      run: cd backend && make format

    - name: Test
      run: cd backend && make test

    - name: Run Go-linter
      uses: golangci/golangci-lint-action@v3

    - name: Build
      run: go build -o server backend/server/server.go 